name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3
    - name: Prerequisites
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install libgtk-3-dev
        fi
      shell: bash
    - name: Switch Compiler
      run: rustup toolchain install nightly
           rustup default nightly
    - name: Build
      run: cargo build --verbose
